### ISSUE TITLE
Module World not Found

### ISSUE THREAD

**Issue by jens1000** [hoodedpaladin/HoodTracker#1]
I created a venv with python 3.8 and installed PySide2.
When I tried to run the tracker with `python HoodTracker.py` I get the following error message:

```
$ python HoodTracker.py 
Traceback (most recent call last):
  File "HoodTracker.py", line 12, in <module>
    from World import World
ModuleNotFoundError: No module named 'World'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HoodTracker.py", line 17, in <module>
    from World import World
ModuleNotFoundError: No module named 'World'
```

**Comment by hoodedpaladin** [comment]
Can you check if HoodTracker/OoT-Randomizer/World.py exists? The official OoT-Randomizer code is included in this project as a git submodule.
If you don't have it, you need to get it, I think that "git submodule update --init --recursive" will do this. And I need to mention that in the readme.
If you do have it, I've screwed up the import-path-changing code here https://github.com/hoodedpaladin/HoodTracker/blob/master/HoodTracker.py#L14

**Comment by jens1000** [comment]
Yes. That was the problem. Thank you.
