### ISSUE TITLE
No module named 'LocationList'

### ISSUE THREAD

**Issue by Link2006** [hoodedpaladin/HoodTracker#2]
I am currently using windows with Python 3.10.8, i also have installed the submodules  and yet when attempting to run HoodTracker, it will fail as it cannot find LocationList.

I've searched in the folder and it seems to be under the OoT-Randomizer submodule instead

**Comment by hoodedpaladin** [comment]
Oops, should be fixed in this commit: https://github.com/hoodedpaladin/HoodTracker/commit/79ec3df12c6d58e7479d91c9da9c3ae1d1a09d87

My IDE runs a little differently than bare python, wish it didn't. Forgot to test the bare python.

**Comment by Link2006** [comment]
Thanks, it works now.
